### ISSUE TITLE
toggle view not working

### ISSUE THREAD

**Issue by johan456789** [ijgnd/anki__browser_side_by_side__horizontal_split#2]
Toggle editor on the bottom/side is not working.

Here's the debug info:

```
Debug info:
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Browser side-by-side horizontal split

Caught exception:
  File "/Users/johan/Library/Application Support/Anki2/addons21/831846358/__init__.py", line 60, in <lambda>
    a.triggered.connect(lambda _, b=self: toggle_orientation(b))
  File "/Users/johan/Library/Application Support/Anki2/addons21/831846358/__init__.py", line 42, in toggle_orientation
    if self.side_by_side:
<class 'AttributeError'>: 'Browser' object has no attribute 'side_by_side'
```

**Comment by ijgnd** [comment]
Thanks for your report. I closed this issue by accident an hour ago but have reopened it.

I can't tell you why this happens.

I have a suspicion that it's a conflict with another add-on. If two add-ons modify the same part of Anki they can't work together. Usually the one that is loaded later takes precedence.

My addon "wraps"/modifies a function that is run when the browser is opened so that my add-on can apply the default setting for the splitter. For this my add-on adds an attribute 'side_by_side'. If another add-on later overwrites this init/startup function of the browser my modification would disappear and not attribute would be added and then when you toggle the editor position you would get the error `'Browser' object has no attribute 'side_by_side'`. But that's just a suspicion. 

I need your help.

1. Disable all other add-ons except for my "Browser: Table/Editor side-by-side (horizontal split)". Then restart Anki so that the disabling takes effect. Then go to the browser. Do you still get this error message? If so my suspicion is wrong ...
2. If the error message disappears with just the "Browser: Table/Editor side-by-side (horizontal split)" add-on it should be an add-on conflict. Ideally you would enable one other add-on, restart, and try again. Repeat this so long until the error message appears. Then post which one was the last add-on you enabled. Also in the main window go to the menu Help -> "About Anki". In the dialog that opens click the "Copy Debug Info" button and publish here what this puts into your clipboard.

**Comment by johan456789** [comment]
[Night Mode](https://ankiweb.net/shared/info/1496166067) is the culprit. 

With Night Mode enabled, the side view is not shown at all, only the bottom view. Trying to toggle the view results in the same exception.

Debug Info:
```
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1

Add-ons:

Search and Replace Tags (disabled)
Night Mode
Remaining time for Anki 21 (disabled)
CrowdAnki JSON exportimport Edit history Collaborate on deck creation
Card Info During Review
Button Colours Good Again
Japanese Support
Replay buttons on card (disabled)
More Overview Stats 21
Browser TableEditor side-by-side horizontal split
AwesomeTTS for Anki 21
Review Heatmap (disabled)
```
> Usually the one that is loaded later takes precedence.

BTW, is the loading order alphabetical? "Night Mode" is indeed after "Browser side-by-side horizontal split."

**Comment by ijgnd** [comment]
Thank you very much for this finding. Compatibility to night mode is important ...

Could you update and try again. The error should no longer appear. There is one limitation that I added to the description: "when the add-on Night Mode is enabled the option "side-by-side is default" of this add-on has no effect.". Does this solve your problem?

The night-mode add-on must be updated for the upcoming Anki version 2.1.17 and as far as I know there are other changes planned for night mode so I want to wait for this new version before I look at the night mode code for a real fix.

**Comment by ijgnd** [comment]
> BTW, is the loading order alphabetical? "Night Mode" is indeed after "Browser side-by-side horizontal split."

No, the folder name is decisive. You don't see folder names in the Anki add-on dialog. For addons downloaded from ankiweb it's the download id.

With night mode it's something different because night mode should be loaded before my add-on. I still need to look at the night mode code though ...

**Comment by johan456789** [comment]
Toggle view now works with Night Mode enabled! Thanks for the quick update.

> There is one limitation that I added to the description: "when the add-on Night Mode is enabled the option "side-by-side is default" of this add-on has no effect.".

A setting that does not work is not a good user experience, and I think people will expect side view by default after installing this add-on.

Is it possible to invoke toggle view shortcut or whatever code it runs automatically when the browser is opened? Maybe a temporary fix if that's not too much work? It's your call, just a suggestion. This is already good enough for me. Thank you for this add-on!

**Comment by ijgnd** [comment]
>  code it runs automatically when the browser is opened?

the night mode code disables my code that is run when the browser is is opened. I attached my code that runs when the browser is opened to a different function that night mode doesn't modify so it should work with night mode now. Let's just hope that I didn't miss some side effects ...

If you find a bug let me know.
